
volumes:
  timescaledb:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg11
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - timescaledb:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: unless-stopped
#    environment:
#      - ADMINER_DEFAULT_SERVER=timescaledb
#    ports:
#      - 1000:8080